#!/bin/bash

echo 'Loading NVM...'
. ~/.nvm/nvm.sh

echo 'Setting node version...'
nvm use

echo 'Starting server...'
json-server --watch server/db.js --middlewares server/not-found.js server/internal-error.js server/less-headers.js
